version: "3.5"

services:
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test_db"
    network_mode: "host"
    volumes:
      - ./data/mysqldata:/var/lib/docker/volumes/mysql_data/_data
    
  rabbitmq:
    image: rabbitmq:3-management
    network_mode: "host"

  client:
    image: flask-client
    depends_on: 
      - rabbitmq
    network_mode: "host"
    
  server:
    image: flask-server
    depends_on:
      - rabbitmq
    network_mode: "host"
  