version: "3.5"

services:
  client:
    image: flask-client
    depends_on: 
      - rabbitmq
    #ports: 
    #  - "5000:5000"
    network_mode: "host"
    
  rabbitmq:
    image: rabbitmq:3-management
    depends_on: 
      - db
    #ports:
    #  - "5672:5672"
    #  - "15672:15672"
    #  - "80:80"
    network_mode: host
  
  db:
    image: mysql:latest
    environment:
      #- MYQL_ROOT_PASSWORD: 123321
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      clearMYSQL_DATABASE: "test_db"
      #MYSQL_USER: "root"
    network_mode: "host"
    #ports:
    #  - "80:80"
  
    volumes:
      - mysql_data:/var/lib/mysql
  
  server:
    image: flask-server
    depends_on:
      - db
    #network_mode: "host"
    # ports:
    # - "80:80"

volumes:
  mysql_data: