FROM ubuntu:22.04

WORKDIR /flask-app

COPY ./server-v1.2.py /flask-app

RUN apt -y update

RUN apt install -y python3-pika

RUN apt install -y python3-mysql.connector

ENTRYPOINT ["python3", "server-v1.2.py"] 