FROM ubuntu:22.04

WORKDIR /flask-app-server

COPY ./server.py /flask-app-server

RUN apt -y update

RUN apt install -y python3-pika

RUN apt install -y python3-mysqldb

ENTRYPOINT ["python3", "server.py"] 